### ISSUE TITLE
Performance of KMeans with multiple cores on Raspberry Pi

### ISSUE THREAD

**Issue by zonca** [sdsc/lightning-tutorials-sc16#1]
I was expecting some performance improvement from using multiple cores:

```
%%time
​
kmeans = KMeans(n_clusters=12, random_state=0, n_jobs=1).fit(workingDF)
CPU times: user 5min 31s, sys: 5min 23s, total: 10min 55s
Wall time: 2min 47s
In [15]:

%%time
​
kmeans = KMeans(n_clusters=12, random_state=0, n_jobs=4).fit(workingDF)
CPU times: user 2.62 s, sys: 2.37 s, total: 4.99 s
Wall time: 3min 4s

```

any suggestion?

**Comment by a1singh** [comment]
It seems context switching is extending the wall time for this process artificially.

total time actually consumed by the process (user + sys time) is much smaller for n_jobs = 4 (4.99s)

**Comment by zonca** [comment]
5 seconds only seems unrealistic, probably `time` is not able to monitor multithreaded code correctly.
